# Generated by Django 3.0.7 on 2020-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('head', models.CharField(default='', max_length=300)),
                ('chead', models.CharField(default='', max_length=300)),
                ('head1', models.CharField(default='', max_length=300)),
                ('head2', models.CharField(default='', max_length=3000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images/')),
            ],
        ),
    ]
