# Generated by Django 3.0.7 on 2020-07-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200713_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.CharField(default=0, max_length=2000),
        ),
    ]
